<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
[{"key" : "A","code" : "A01","name" : "광장비"},                                            
{"key" : "A","code" : "A02","name" : "동축장비"},                                          
{"key" : "A","code" : "A03","name" : "HE자재"},                                            
{"key" : "A","code" : "A04","name" : "케이블"},                                            
{"key" : "A","code" : "A05","name" : "전원장비"},                                          
{"key" : "A","code" : "A06","name" : "수동소자"},                                          
{"key" : "A","code" : "A07","name" : "동축자재"},                                          
{"key" : "A","code" : "A08","name" : "필터,감쇄기"},                                       
{"key" : "B","code" : "B01","name" : "CMTS"},                                              
{"key" : "B","code" : "B02","name" : "백본장비"},                                          
{"key" : "B","code" : "B03","name" : "백본스위치"},                                        
{"key" : "B","code" : "B04","name" : "Server"},                                            
{"key" : "B","code" : "B05","name" : "Switch"},                                            
{"key" : "C","code" : "C03","name" : "아날로그 H/E"},                                      
{"key" : "B","code" : "B07","name" : "VDSL"},                                              
{"key" : "C","code" : "C05","name" : "주조정실"},                                          
{"key" : "B","code" : "B09","name" : "허브"},                                              
{"key" : "C","code" : "C01","name" : "컨버터"},                                            
{"key" : "D","code" : "D01","name" : "사무장비"},                                          
{"key" : "D","code" : "D02","name" : "사무용품"},                                          
{"key" : "B","code" : "B14","name" : "보안장비"},                                          
{"key" : "A","code" : "A09","name" : "광자재"},                                            
{"key" : "C","code" : "C02","name" : "셋탑박스"},                                          
{"key" : "B","code" : "B10","name" : "CM"},                                                
{"key" : "B","code" : "B11","name" : "VoIP"},                                              
{"key" : "A","code" : "A10","name" : "관로자재"},                                          
{"key" : "A","code" : "A11","name" : "일반노무"},                                          
{"key" : "B","code" : "B12","name" : "미디어컨버터"},                                      
{"key" : "C","code" : "C04","name" : "디지털 H/E"},                                        
{"key" : "C","code" : "C06","name" : "스튜디오"},                                          
{"key" : "C","code" : "C07","name" : "부조정실"},                                          
{"key" : "C","code" : "C08","name" : "종합편집실"},                                        
{"key" : "C","code" : "C09","name" : "중계시스템"},                                        
{"key" : "C","code" : "C10","name" : "가편집실"},                                          
{"key" : "C","code" : "C11","name" : "전력설비"},                                          
{"key" : "C","code" : "C12","name" : "공조설비"},                                          
{"key" : "C","code" : "C13","name" : "기타의 방송설비"},                                   
{"key" : "B","code" : "B13","name" : "PLC"},                                               
{"key" : "A","code" : "A12","name" : "계측기/공구"},                                       
{"key" : "A","code" : "A13","name" : "기타자재"},                                          
{"key" : "C","code" : "C14","name" : "Camera"},                                            
{"key" : "D","code" : "D04","name" : "기타장비"},                                          
{"key" : "C","code" : "C15","name" : "Video"},                                             
{"key" : "B","code" : "B15","name" : "기타인터넷장비"},                                    
{"key" : "B","code" : "B16","name" : "FMS(환경감시 시스템)"},                              
{"key" : "B","code" : "B17","name" : "QOS장비"},                                           
{"key" : "B","code" : "B18","name" : "전원장비 및 설비"},                                  
{"key" : "B","code" : "B19","name" : "VPN장비"},                                           
{"key" : "Z","code" : "ZZZ","name" : "값없음"}]