<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
[{"key" : "B11","code" : "B11004","name" : "VoIP Trunk Gateway 16 E1 Module"},                   
{"key" : "D01","code" : "D01002","name" : "NOTEBOOK"},                                          
{"key" : "D01","code" : "D01003","name" : "MONITOR"},                                           
{"key" : "D01","code" : "D01004","name" : "프린터"},                                            
{"key" : "A07","code" : "A07061","name" : "기타자재"},                                          
{"key" : "A10","code" : "A10001","name" : "맨홀"},                                              
{"key" : "A10","code" : "A10003","name" : "수공철개"},                                          
{"key" : "A10","code" : "A10002","name" : "인공철개"},                                          
{"key" : "A10","code" : "A10004","name" : "곡관"},                                              
{"key" : "A10","code" : "A10005","name" : "방수관"},                                            
{"key" : "A10","code" : "A10006","name" : "FC관"},                                              
{"key" : "A10","code" : "A10007","name" : "PE전선관"},                                          
{"key" : "A10","code" : "A10008","name" : "COD관"},                                             
{"key" : "A10","code" : "A10009","name" : "경고테이프"},                                        
{"key" : "A03","code" : "A03013","name" : "랙"},                                                
{"key" : "A07","code" : "A07062","name" : "플랙시블전선관"},                                    
{"key" : "B02","code" : "B02008","name" : "OSR-7606"},                                          
{"key" : "D01","code" : "D01005","name" : "스캐너"},                                            
{"key" : "A07","code" : "A07063","name" : "누전차단기"},                                        
{"key" : "A11","code" : "A11025","name" : "포트이설(절체) 작업"},                               
{"key" : "A07","code" : "A07064","name" : "계량기"},                                            
{"key" : "A11","code" : "A11026","name" : "드릴 작업"},                                         
{"key" : "D01","code" : "D01006","name" : "소프트웨어"},                                        
{"key" : "A11","code" : "A11027","name" : "필터 작업"},                                         
{"key" : "A11","code" : "A11007","name" : "광케이블 작업"},                                     
{"key" : "C06","code" : "C06001","name" : "Portable Unit"},                                     
{"key" : "A11","code" : "A11009","name" : "전송장비 시험"},                                     
{"key" : "A11","code" : "A11010","name" : "케이블 작업"},                                       
{"key" : "A11","code" : "A11011","name" : "포박 작업"},                                         
{"key" : "A11","code" : "A11012","name" : "접지 작업"},                                         
{"key" : "A11","code" : "A11013","name" : "전기 작업"},                                         
{"key" : "A11","code" : "A11014","name" : "수동소자 작업"},                                     
{"key" : "A11","code" : "A11015","name" : "인입관로 작업"},                                     
{"key" : "C06","code" : "C06002","name" : "Headset"},                                           
{"key" : "C06","code" : "C06003","name" : "Battery Charger"},                                   
{"key" : "C06","code" : "C06004","name" : "생활무전기"},                                        
{"key" : "C06","code" : "C06005","name" : "Vinten Pedestal"},                                   
{"key" : "C07","code" : "C07002","name" : "DigitalCosmos System"},                              
{"key" : "C07","code" : "C07003","name" : "DigitalCosmos SE"},                                  
{"key" : "C07","code" : "C07004","name" : "2-CH Main Station"},                                 
{"key" : "C07","code" : "C07005","name" : "INTERFACE"},                                         
{"key" : "C07","code" : "C07006","name" : "GOOSENECK MIC"},                                     
{"key" : "B12","code" : "B12001","name" : "Efomc-RM"},                                          
{"key" : "B12","code" : "B12002","name" : "Efomc-WDM-C"},                                       
{"key" : "B12","code" : "B12003","name" : "Efomc-WDM-S"},                                       
{"key" : "B12","code" : "B12004","name" : "20Km Wdm, 1CORE MEDIACONVERTER"},                    
{"key" : "B12","code" : "B12005","name" : "20Km Wdm, 2CORE MEDIACONVERTER"},                    
{"key" : "C07","code" : "C07007","name" : "MATRIX TELERHONE INTERFACE"},                        
{"key" : "C06","code" : "C06006","name" : "Digital Camcorder"},                                 
{"key" : "C09","code" : "C09001","name" : "MPEG 2 Encoder"},                                    
{"key" : "C09","code" : "C09002","name" : "DOWN LOAD PC"},                                      
{"key" : "C03","code" : "C03001","name" : "아날로그 변조기"},                                   
{"key" : "C05","code" : "C05001","name" : "Video Patchbay"},                                    
{"key" : "C05","code" : "C05002","name" : "Audio Patchbay"},                                    
{"key" : "C05","code" : "C05003","name" : "Video Distributor Amplifier"},                       
{"key" : "C05","code" : "C05004","name" : "Audio Distributor Amplifier"},                       
{"key" : "C05","code" : "C05008","name" : "Multi Viewer"},                                      
{"key" : "A09","code" : "A09021","name" : "110블럭"},                                           
{"key" : "A11","code" : "A11029","name" : "패치판넬 작업"},                                     
{"key" : "A09","code" : "A09020","name" : "패치판넬"},                                          
{"key" : "A09","code" : "A09022","name" : "110블럭브라켓"},                                     
{"key" : "A07","code" : "A07065","name" : "트레이"},                                            
{"key" : "A11","code" : "A11028","name" : "UTP 케이블 작업"},                                   
{"key" : "A07","code" : "A07066","name" : "동관단자"},                                          
{"key" : "C12","code" : "C12001","name" : "에어컨"},                                            
{"key" : "C11","code" : "C11001","name" : "UPS"},                                               
{"key" : "D01","code" : "D01007","name" : "빔프로젝터"},                                        
{"key" : "A09","code" : "A09023","name" : "CWDM(광접속함체용)"},                                
{"key" : "A09","code" : "A09024","name" : "DWDM(광접속함체용)"},                                
{"key" : "A09","code" : "A09025","name" : "OAM"},                                               
{"key" : "D01","code" : "D01008","name" : "DDR2 256MB"},                                        
{"key" : "D01","code" : "D01009","name" : "DDR2 512MB"},                                        
{"key" : "A09","code" : "A09026","name" : "WDM하우징"},                                         
{"key" : "C05","code" : "C05009","name" : "광고삽입기"},                                        
{"key" : "C11","code" : "C11002","name" : "발전기"},                                            
{"key" : "C11","code" : "C11003","name" : "발전기 트레일러"},                                   
{"key" : "B07","code" : "B07003","name" : "아답터"},                                            
{"key" : "D01","code" : "D01010","name" : "USB 메모리"},                                        
{"key" : "D01","code" : "D01011","name" : "외장형하드"},                                        
{"key" : "B13","code" : "B13001","name" : "PLC모뎀"},                                           
{"key" : "B12","code" : "B12006","name" : "CS-SMC-샤시"},                                       
{"key" : "B12","code" : "B12007","name" : "CS-SMC-단독형"},                                     
{"key" : "B12","code" : "B12008","name" : "SC-SMC-집합형"},                                     
{"key" : "D01","code" : "D01012","name" : "HDD(데스크탑용)"},                                   
{"key" : "D01","code" : "D01013","name" : "DDR 512MB"},                                         
{"key" : "B07","code" : "B07004","name" : "텔슨아답터"},                                        
{"key" : "B01","code" : "B01003","name" : "Cadant C4"},                                         
{"key" : "C03","code" : "C03002","name" : "STEREO MODULATOR"},                                  
{"key" : "C03","code" : "C03003","name" : "아날로그 신호처리기"},                               
{"key" : "A09","code" : "A09027","name" : "블럭단자"},                                          
{"key" : "A12","code" : "A12001","name" : "스펙트럼 아날라이저"},                               
{"key" : "A09","code" : "A09028","name" : "블럭단자 고정구"},                                   
{"key" : "C01","code" : "C01004","name" : "컨버터"},                                            
{"key" : "C05","code" : "C05010","name" : "디코더 보드"},                                       
{"key" : "A11","code" : "A11030","name" : "VDSL 작업"},                                         
{"key" : "A07","code" : "A07067","name" : "유니트(전화)"},                                      
{"key" : "B01","code" : "B01004","name" : "BW3500"},                                            
{"key" : "C05","code" : "C05011","name" : "Console"},                                           
{"key" : "C05","code" : "C05012","name" : "Digital Clock"},                                     
{"key" : "A10","code" : "A10010","name" : "잠금장치"},                                          
{"key" : "A10","code" : "A10011","name" : "철개속뚜껑"},                                        
{"key" : "A03","code" : "A03014","name" : "선택기"},                                            
{"key" : "A13","code" : "A13001","name" : "반사시트"},                                          
{"key" : "C05","code" : "C05013","name" : "MCS"},                                               
{"key" : "C04","code" : "C04001","name" : "MCS(기남)"},                                         
{"key" : "C04","code" : "C04002","name" : "MCS(한빛)"},                                         
{"key" : "C05","code" : "C05014","name" : "MCS(남동)"},                                         
{"key" : "C05","code" : "C05015","name" : "MCS(서해)"},                                         
{"key" : "C04","code" : "C04003","name" : "MCS(새롬)"},                                         
{"key" : "C05","code" : "C05016","name" : "MCS(중부)"},                                         
{"key" : "C04","code" : "C04004","name" : "MCS(전주)"},                                         
{"key" : "C05","code" : "C05017","name" : "MCS(서부산)"},                                       
{"key" : "D01","code" : "D01014","name" : "복합기"},                                            
{"key" : "B01","code" : "B01005","name" : "BW3200"},                                            
{"key" : "B01","code" : "B01006","name" : "UBR7223"},                                           
{"key" : "B01","code" : "B01007","name" : "UBR7200용 라인카드"},                                
{"key" : "B01","code" : "B01008","name" : "TERA1000"},                                          
{"key" : "D04","code" : "D04001","name" : "바코드시스템"},                                      
{"key" : "B04","code" : "B04002","name" : "HP_COMPAQ서버"},                                     
{"key" : "C03","code" : "C03004","name" : "디지털 신호처리기"},                                 
{"key" : "C04","code" : "C04005","name" : "QAM 변조기"},                                        
{"key" : "C04","code" : "C04006","name" : "실시간 Encoder"},                                    
{"key" : "C05","code" : "C05018","name" : "Multi Keyer"},                                       
{"key" : "C05","code" : "C05019","name" : "문자발생기"},                                        
{"key" : "C05","code" : "C05020","name" : "송출서버"},                                          
{"key" : "C05","code" : "C05021","name" : "VCR"},                                               
{"key" : "C05","code" : "C05022","name" : "IP Decoder"},                                        
{"key" : "C14","code" : "C14001","name" : "EFP Camera"},                                        
{"key" : "C14","code" : "C14002","name" : "ENG Camera"},                                        
{"key" : "C15","code" : "C15001","name" : "VCR-Analog"},                                        
{"key" : "C15","code" : "C15002","name" : "VCR-Digital"},                                       
{"key" : "C15","code" : "C15003","name" : "switcher / Analog"},                                 
{"key" : "C15","code" : "C15004","name" : "Editor"},                                            
{"key" : "C15","code" : "C15005","name" : "계측기"},                                            
{"key" : "C15","code" : "C15006","name" : "문자발생기"},                                        
{"key" : "C16","code" : "C16001","name" : "Audio Mixer"},                                       
{"key" : "C14","code" : "C14003","name" : "Pedestal"},                                          
{"key" : "C12","code" : "C12002","name" : "환풍기"},                                            
{"key" : "B01","code" : "B01009","name" : "업컨버터"},                                          
{"key" : "E01","code" : "E01001","name" : "M/S EA 1년 또는 신규 (XP+OFFFIE)"},                  
{"key" : "E01","code" : "E01002","name" : "M/S EA Ture Up 1년 (XP+OFFICE)"},                    
{"key" : "E01","code" : "E01003","name" : "M/S Win SQL Server Std Kor MVL"},                    
{"key" : "E01","code" : "E01004","name" : "M/S Project Std Win Kor MVL"},                       
{"key" : "E01","code" : "E01005","name" : "한글 2005(ILA)"},                                    
{"key" : "E01","code" : "E01006","name" : "Trend Micro 백신(Neat Suite)"},                      
{"key" : "E01","code" : "E01007","name" : "Adobe After effect pb 7.0 (IBM 또는 MAC)"},          
{"key" : "E01","code" : "E01008","name" : "Adobe Photoshop CS (IBM 또는 MAC)"},                 
{"key" : "E01","code" : "E01009","name" : "Adobe Acrobat 7.0"},                                 
{"key" : "E01","code" : "E01010","name" : "Adobe lllustrator CS (IBM 또는 MAC)"},               
{"key" : "E01","code" : "E01011","name" : "Adobe Premiere Pro"},                                
{"key" : "E01","code" : "E01012","name" : "Adobe Audition 1.5"},                                
{"key" : "E01","code" : "E01013","name" : "Adobe Creative Suites Prem"},                        
{"key" : "E01","code" : "E01014","name" : "Adobe Captivate Win Eng"},                           
{"key" : "E01","code" : "E01015","name" : "Micromedia Dream Weaver MX"},                        
{"key" : "E01","code" : "E01016","name" : "Micromedia Flash MX"},                               
{"key" : "E01","code" : "E01017","name" : "Oracle 9i-Client Std (최대 2CPU 10User 기본)"},      
{"key" : "E01","code" : "E01018","name" : "ER Win"},                                            
{"key" : "E01","code" : "E01019","name" : "Toad for Oracle Std 8.0"},                           
{"key" : "E01","code" : "E01020","name" : "Nero 6"},                                            
{"key" : "E01","code" : "E01021","name" : "한글 ACD See 7.0"},                                  
{"key" : "E01","code" : "E01022","name" : "Al Tools"},                                          
{"key" : "E01","code" : "E01023","name" : "Al Zip"},                                            
{"key" : "E01","code" : "E01024","name" : "Al See"},                                            
{"key" : "E01","code" : "E01025","name" : "Al FTP"},                                            
{"key" : "E01","code" : "E01026","name" : "Ultra Edit"},                                        
{"key" : "E01","code" : "E01027","name" : "EDIT PLUS"},                                         
{"key" : "E01","code" : "E01028","name" : "Secure CRT"},                                        
{"key" : "E01","code" : "E01029","name" : "CRT"},                                               
{"key" : "E01","code" : "E01030","name" : "노터스노츠(Client)"},                                
{"key" : "E01","code" : "E01031","name" : "Golden"},                                            
{"key" : "E01","code" : "E01032","name" : "Solarwinds Broadband Solution (1년 유지보수 포함)"}, 
{"key" : "E01","code" : "E01033","name" : "Snm PC 7.0 Ent Edition (Remote Console 1EA씩 포함)"},
{"key" : "E01","code" : "E01034","name" : "Swishmax singleuser - ESD"},                         
{"key" : "E01","code" : "E01035","name" : "SQL Gate for MYspl"},                                
{"key" : "E01","code" : "E01036","name" : "Particle illusion 3.0"},                             
{"key" : "E01","code" : "E01037","name" : "PDF Creative"},                                      
{"key" : "E01","code" : "E01038","name" : "Myclipse 4.1.1-GA"},                                 
{"key" : "A09","code" : "A09029","name" : "광점퍼코드여장함"},                                  
{"key" : "A12","code" : "A12002","name" : "디지털신호 분석메타"},                               
{"key" : "A01","code" : "A01049","name" : "GMX1004"},                                           
{"key" : "A01","code" : "A01050","name" : "FNU-0604"},                                          
{"key" : "A01","code" : "A01051","name" : "PSU-030-AC/5"},                                      
{"key" : "A12","code" : "A12003","name" : "광원계"},                                            
{"key" : "A12","code" : "A12004","name" : "광파워메타"},                                        
{"key" : "A12","code" : "A12005","name" : "O T D R"},                                           
{"key" : "A12","code" : "A12006","name" : "신호레벨메타"},                                      
{"key" : "A01","code" : "A01052","name" : "WDM 커플러"},                                        
{"key" : "B02","code" : "B02009","name" : "Catalyst-4000"},                                     
{"key" : "A13","code" : "A13002","name" : "기타자재/기타노무"},                                 
{"key" : "B05","code" : "B05028","name" : "기타스위치"},                                        
{"key" : "B04","code" : "B04003","name" : "기타서버"},                                          
{"key" : "D01","code" : "D01015","name" : "PBX"},                                               
{"key" : "D01","code" : "D01016","name" : "사무용허브"},                                        
{"key" : "C05","code" : "C05025","name" : "컨텐츠전송장비"},                                    
{"key" : "C05","code" : "C05023","name" : "TV 및 Monitor"},                                     
{"key" : "C05","code" : "C05024","name" : "장비 Control PC"},                                   
{"key" : "C12","code" : "C12003","name" : "항온항습기"},                                        
{"key" : "C14","code" : "C14004","name" : "기타카메라장치"},                                    
{"key" : "C16","code" : "C16002","name" : "AMP"},                                               
{"key" : "C15","code" : "C15007","name" : "기타비디오장비"},                                    
{"key" : "C06","code" : "C06007","name" : "조명장비"},                                          
{"key" : "C16","code" : "C16003","name" : "기타오디오장비"},                                    
{"key" : "C04","code" : "C04007","name" : "디지털광고삽입기"},                                  
{"key" : "C04","code" : "C04008","name" : "아날로그광고삽입기(CMLink1000)"},                    
{"key" : "A12","code" : "A12007","name" : "아나로그신호 분석메타"},                             
{"key" : "A13","code" : "A13003","name" : "페디스탈"},                                          
{"key" : "A12","code" : "A12008","name" : "광융합접속기"},                                      
{"key" : "A12","code" : "A12009","name" : "공구가방"},                                          
{"key" : "A12","code" : "A12010","name" : "압착툴"},                                            
{"key" : "A12","code" : "A12011","name" : "탈피기"},                                            
{"key" : "A12","code" : "A12012","name" : "락더미키"},                                          
{"key" : "A12","code" : "A12013","name" : "니퍼"},                                              
{"key" : "A12","code" : "A12014","name" : "쪽가위"},                                            
{"key" : "A12","code" : "A12015","name" : "롱노우즈 플라이어"},                                 
{"key" : "A12","code" : "A12016","name" : "드라이버"},                                          
{"key" : "A12","code" : "A12017","name" : "망치"},                                              
{"key" : "A12","code" : "A12018","name" : "쇠톱"},                                              
{"key" : "A12","code" : "A12019","name" : "조정봉"},                                            
{"key" : "A12","code" : "A12020","name" : "드릴"},                                              
{"key" : "A12","code" : "A12021","name" : "드릴날"},                                            
{"key" : "A12","code" : "A12022","name" : "스패너"},                                            
{"key" : "A12","code" : "A12023","name" : "커터칼"},                                            
{"key" : "A12","code" : "A12024","name" : "랜테스터"},                                          
{"key" : "A12","code" : "A12025","name" : "랜랩핑기"},                                          
{"key" : "A12","code" : "A12026","name" : "랜신호테스터"},                                      
{"key" : "A12","code" : "A12027","name" : "전원테스터"},                                        
{"key" : "A12","code" : "A12028","name" : "토크렌치"},                                          
{"key" : "A12","code" : "A12029","name" : "펜치"},                                              
{"key" : "A12","code" : "A12030","name" : "상향신호발생기"},                                    
{"key" : "A12","code" : "A12031","name" : "수리보"},                                            
{"key" : "A12","code" : "A12032","name" : "토치"},                                              
{"key" : "A12","code" : "A12033","name" : "복스"},                                              
{"key" : "A12","code" : "A12034","name" : "필터키"},                                            
{"key" : "A12","code" : "A12035","name" : "인터넷품질측정장비"},                                
{"key" : "B12","code" : "B12009","name" : "기타미디어컨버터"},                                  
{"key" : "B02","code" : "B02010","name" : "CISCO7200"},                                         
{"key" : "A02","code" : "A02019","name" : "상향등화기(오가트)"},                                
{"key" : "A02","code" : "A02020","name" : "하향등화기(오가트)"},                                
{"key" : "A02","code" : "A02021","name" : "하향역등화기(오가트)"},                              
{"key" : "A02","code" : "A02022","name" : "감쇄기(오가트)"},                                    
{"key" : "B09","code" : "B09001","name" : "NSH800"},                                            
{"key" : "B02","code" : "B02011","name" : "Cisco기타스위치"},                                   
{"key" : "A12","code" : "A12036","name" : "광심선대조기"},                                      
{"key" : "A12","code" : "A12037","name" : "기타계측기"},                                        
{"key" : "B10","code" : "B10008","name" : "Wireless Cable Modem"},                              
{"key" : "A02","code" : "A02023","name" : "감쇄기(넷웨이브)"},                                  
{"key" : "B01","code" : "B01010","name" : "기타CMTS"},                                          
{"key" : "D01","code" : "D01017","name" : "기타장비"},                                          
{"key" : "A02","code" : "A02024","name" : "상향등화기(넷웨이브)"},                              
{"key" : "A02","code" : "A02025","name" : "하향등화기(넷웨이브)"},                              
{"key" : "B02","code" : "B02012","name" : "Cisco기타라우터"},                                   
{"key" : "B14","code" : "B14001","name" : "보안장비"},                                          
{"key" : "C02","code" : "C02007","name" : "컴포넌트 케이블"},                                   
{"key" : "B15","code" : "B15001","name" : "인터넷카메라"},                                      
{"key" : "A07","code" : "A07068","name" : "체신밴드"},                                          
{"key" : "D01","code" : "D01018","name" : "노트북용 Harddisk(80G)"},                            
{"key" : "D01","code" : "D01019","name" : "노트북용 RAM(1GB)"},                                 
{"key" : "D01","code" : "D01020","name" : "마우스(USB타입)"},                                   
{"key" : "C15","code" : "C15008","name" : "이동영상차량장비"},                                  
{"key" : "B05","code" : "B05029","name" : "L3-7012G-AC"},                                       
{"key" : "D01","code" : "D01021","name" : "Memory"},                                            
{"key" : "A09","code" : "A09030","name" : "광분기기"},                                          
{"key" : "A13","code" : "A13004","name" : "덕트"},                                              
{"key" : "B05","code" : "B05030","name" : "P7024G-AC"},                                         
{"key" : "B10","code" : "B10009","name" : "SA 케이블모뎀"},                                     
{"key" : "A12","code" : "A12038","name" : "손전등"},                                            
{"key" : "A12","code" : "A12039","name" : "콘솔"},                                              
{"key" : "A12","code" : "A12040","name" : "광컨넥터 클리너"},                                   
{"key" : "A12","code" : "A12041","name" : "LAN툴"},                                             
{"key" : "A12","code" : "A12042","name" : "LAN탈피기"},                                         
{"key" : "D04","code" : "D04002","name" : "디지털카메라"},                                      
{"key" : "A12","code" : "A12045","name" : "안전화"},                                            
{"key" : "A12","code" : "A12043","name" : "안전벨트"},                                          
{"key" : "A12","code" : "A12044","name" : "안전모"},                                            
{"key" : "A12","code" : "A12046","name" : "접지저항테스터"},                                    
{"key" : "A12","code" : "A12047","name" : "광컨넥터 릴클리너"},                                 
{"key" : "A12","code" : "A12048","name" : "타카"},                                              
{"key" : "A12","code" : "A12049","name" : "펀치다운툴"},                                        
{"key" : "A12","code" : "A12050","name" : "가스 글루건"},                                       
{"key" : "A12","code" : "A12051","name" : "요비선"},                                            
{"key" : "A11","code" : "A11031","name" : "절체 작업"},                                         
{"key" : "C05","code" : "C05026","name" : "기타 주조정실장비"},                                 
{"key" : "C12","code" : "C12004","name" : "자동소화설비"},                                      
{"key" : "C12","code" : "C12005","name" : "나프타패키지"},                                      
{"key" : "C17","code" : "C17001","name" : "자동소화설비노무비"},                                
{"key" : "A01","code" : "A01022","name" : "하향광송신기"},                                      
{"key" : "A07","code" : "A07050","name" : "U볼트"},                                             
{"key" : "A08","code" : "A08004","name" : "HIGH PASS 필터 "},                                   
{"key" : "A07","code" : "A07001","name" : "각암타이"},                                          
{"key" : "A07","code" : "A07002","name" : "강관주"},                                            
{"key" : "A07","code" : "A07003","name" : "강관주 밴드"},                                       
{"key" : "A07","code" : "A07004","name" : "경완금"},                                            
{"key" : "A07","code" : "A07005","name" : "근가블럭"},                                          
{"key" : "A07","code" : "A07006","name" : "마크(네임)타이"},                                    
{"key" : "A07","code" : "A07007","name" : "명찰"},                                              
{"key" : "A07","code" : "A07008","name" : "바인더선"},                                          
{"key" : "A07","code" : "A07009","name" : "반경관"},                                            
{"key" : "A07","code" : "A07010","name" : "반경관밴드"},                                        
{"key" : "A07","code" : "A07011","name" : "발판볼트"},                                          
{"key" : "A07","code" : "A07012","name" : "캡"},                                                
{"key" : "A07","code" : "A07013","name" : "서비스커넥터"},                                      
{"key" : "A07","code" : "A07014","name" : "스탬플"},                                            
{"key" : "A07","code" : "A07015","name" : "스파이럴슬리브"},                                    
{"key" : "A07","code" : "A07016","name" : "스펜클램프"},                                        
{"key" : "A07","code" : "A07017","name" : "아이너트"},                                          
{"key" : "A07","code" : "A07018","name" : "암타이밴드"},                                        
{"key" : "A07","code" : "A07019","name" : "앙카볼트"},                                          
{"key" : "A07","code" : "A07020","name" : "열수축관"},                                          
{"key" : "A07","code" : "A07021","name" : "와이어링크"},                                        
{"key" : "A07","code" : "A07022","name" : "와이어바이스"},                                      
{"key" : "A07","code" : "A07023","name" : "인식표"},                                            
{"key" : "A07","code" : "A07024","name" : "인입벽철"},                                          
{"key" : "A07","code" : "A07025","name" : "인입선클램프"},                                      
{"key" : "A07","code" : "A07026","name" : "장볼트"},                                            
{"key" : "A07","code" : "A07027","name" : "전기선"},                                            
{"key" : "A07","code" : "A07028","name" : "절연테이프"},                                        
{"key" : "A07","code" : "A07029","name" : "접지동봉"},                                          
{"key" : "A07","code" : "A07030","name" : "접지러그"},                                          
{"key" : "A07","code" : "A07031","name" : "접지볼트"},                                          
{"key" : "A07","code" : "A07032","name" : "접지선"},                                            
{"key" : "A07","code" : "A07033","name" : "접지커넥터"},                                        
{"key" : "A01","code" : "A01025","name" : "ADD/DROP MUX"},                                      
{"key" : "A01","code" : "A01026","name" : "BDR Upgrade Kit"},                                   
{"key" : "A01","code" : "A01028","name" : "BDR수신기프로세서"},                                 
{"key" : "A01","code" : "A01030","name" : "DWDM MUX"},                                          
{"key" : "A01","code" : "A01032","name" : "GIGALight DWDM Digital송신기"},                      
{"key" : "A01","code" : "A01034","name" : "H/E AMP"},                                           
{"key" : "A01","code" : "A01036","name" : "Link Extender (CN 3dB보상)"},                        
{"key" : "A01","code" : "A01038","name" : "MEDIA CONVERTER(H/E)"},                              
{"key" : "A01","code" : "A01040","name" : "MUX(1×2)"},                                         
{"key" : "A01","code" : "A01042","name" : "MUX(1×8)"},                                         
{"key" : "A01","code" : "A01043","name" : "MUX/DEMUX 프레임"},                                  
{"key" : "A01","code" : "A01045","name" : "RF자동절체기"},                                      
{"key" : "A01","code" : "A01047","name" : "SHELF"},                                             
{"key" : "A01","code" : "A01027","name" : "BDR수신기모듈"},                                     
{"key" : "A01","code" : "A01029","name" : "DWDM DEMUX"},                                        
{"key" : "A01","code" : "A01031","name" : "GIGALight DWDM Digital송수신기"},                    
{"key" : "A01","code" : "A01033","name" : "GIGALight DWDM Digital수신기"},                      
{"key" : "A01","code" : "A01035","name" : "HOUSING"},                                           
{"key" : "A01","code" : "A01037","name" : "MEDIA CONVERTER(가입자)"},                           
{"key" : "A01","code" : "A01039","name" : "MUX HOUSING"},                                       
{"key" : "A01","code" : "A01041","name" : "MUX(1×4)"},                                         
{"key" : "A01","code" : "A01044","name" : "ONU"},                                               
{"key" : "A01","code" : "A01046","name" : "SG2용 3분할보드"},                                   
{"key" : "A02","code" : "A02001","name" : "간선증폭기"},                                        
{"key" : "A02","code" : "A02003","name" : "감쇄기(SA)"},                                        
{"key" : "A02","code" : "A02006","name" : "상향등화기(모토로라)"},                              
{"key" : "A02","code" : "A02008","name" : "상향모듈"},                                          
{"key" : "A02","code" : "A02011","name" : "하향등화기(모토로라)"},                              
{"key" : "A02","code" : "A02013","name" : "하향역등화기(모토로라)"},                            
{"key" : "A02","code" : "A02015","name" : "AGC"},                                               
{"key" : "A03","code" : "A03002","name" : "섀시"},                                              
{"key" : "A03","code" : "A03004","name" : "EQ(PCI)"},                                           
{"key" : "A03","code" : "A03006","name" : "H/E 결합기"},                                        
{"key" : "A03","code" : "A03008","name" : "H/E 분배,결합기"},                                   
{"key" : "A03","code" : "A03010","name" : "H/E AMP"},                                           
{"key" : "A04","code" : "A04001","name" : "동축케이블"},                                        
{"key" : "A04","code" : "A04003","name" : "UTP케이블"},                                         
{"key" : "A05","code" : "A05003","name" : "전원공급기(UPS)"},                                   
{"key" : "A06","code" : "A06001","name" : "구망-분배분기기"},                                   
{"key" : "A06","code" : "A06003","name" : "08 TAP-OFF"},                                        
{"key" : "A06","code" : "A06006","name" : "옥내용 1분기기"},                                    
{"key" : "A06","code" : "A06008","name" : "옥내용 4분기기"},                                    
{"key" : "A06","code" : "A06010","name" : "옥내용분배기"},                                      
{"key" : "A07","code" : "A07034","name" : "조가선"},                                            
{"key" : "A07","code" : "A07036","name" : "조선접속클램프"},                                    
{"key" : "A07","code" : "A07038","name" : "지선밴드"},                                          
{"key" : "A07","code" : "A07041","name" : "케이블행거"},                                        
{"key" : "A07","code" : "A07043","name" : "턴버클"},                                            
{"key" : "A07","code" : "A07048","name" : "PVC 파이프"},                                        
{"key" : "A01","code" : "A01002","name" : "1X2 DWDM Multiplexer"},                              
{"key" : "A01","code" : "A01004","name" : "1X4 DWDM Multiplexer"},                              
{"key" : "A01","code" : "A01006","name" : "1X8 DWDM Multiplexer"},                              
{"key" : "A01","code" : "A01008","name" : "광수신기"},                                          
{"key" : "A01","code" : "A01011","name" : "등화기"},                                            
{"key" : "A01","code" : "A01013","name" : "메인프레임"},                                        
{"key" : "A01","code" : "A01015","name" : "상향광수신기"},                                      
{"key" : "A01","code" : "A01017","name" : "수신기 냉각팬"},                                     
{"key" : "A01","code" : "A01020","name" : "점퍼코드 매니지먼트"},                               
{"key" : "A01","code" : "A01023","name" : "하향광수신기"},                                      
{"key" : "A07","code" : "A07049","name" : "U밴드"},                                             
{"key" : "A08","code" : "A08003","name" : "BAND PASS 필터 "},                                   
{"key" : "A08","code" : "A08006","name" : "LOW PASS 필터 "},                                    
{"key" : "A02","code" : "A02002","name" : "감쇄기(모토로라)"},                                  
{"key" : "A02","code" : "A02004","name" : "구내증폭기"},                                        
{"key" : "A02","code" : "A02005","name" : "분배기"},                                            
{"key" : "A02","code" : "A02007","name" : "상향등화기(SA)"},                                    
{"key" : "A02","code" : "A02009","name" : "선로증폭기"},                                        
{"key" : "A02","code" : "A02010","name" : "연장증폭기"},                                        
{"key" : "A02","code" : "A02012","name" : "하향등화기(SA)"},                                    
{"key" : "A02","code" : "A02014","name" : "하향역등화기(SA)"},                                  
{"key" : "A03","code" : "A03001","name" : "모듈레이터(변조기)"},                                
{"key" : "A03","code" : "A03003","name" : "채널셀렉터(화면분할기)"},                            
{"key" : "A03","code" : "A03005","name" : "EXTENDED F CONNECTOR DRIVER"},                       
{"key" : "A03","code" : "A03007","name" : "H/E 방향성결합기"},                                  
{"key" : "A03","code" : "A03009","name" : "H/E 분배기"},                                        
{"key" : "A03","code" : "A03011","name" : "PAD(PCI)"},                                          
{"key" : "A03","code" : "A03012","name" : "POWER SUPPLY"},                                      
{"key" : "A04","code" : "A04002","name" : "광케이블"},                                          
{"key" : "A05","code" : "A05001","name" : "밧데리"},                                            
{"key" : "A05","code" : "A05002","name" : "전원공급기(PS)"},                                    
{"key" : "A05","code" : "A05004","name" : "UPS 받침대"},                                        
{"key" : "A06","code" : "A06002","name" : "04 TAP-OFF"},                                        
{"key" : "A06","code" : "A06004","name" : "16 TAP-OFF"},                                        
{"key" : "A06","code" : "A06005","name" : "방향성결합기"},                                      
{"key" : "A06","code" : "A06007","name" : "옥내용 2분기기"},                                    
{"key" : "A06","code" : "A06009","name" : "옥내용 8분기기"},                                    
{"key" : "A06","code" : "A06011","name" : "옥외용분배기"},                                      
{"key" : "A06","code" : "A06012","name" : "전력삽입기"},                                        
{"key" : "A07","code" : "A07035","name" : "조선인류클램프"},                                    
{"key" : "A07","code" : "A07037","name" : "종단기"},                                            
{"key" : "A07","code" : "A07039","name" : "커넥터"},                                            
{"key" : "A07","code" : "A07040","name" : "케이블타이"},                                        
{"key" : "A07","code" : "A07042","name" : "탭브라켓(스탠)"},                                    
{"key" : "A07","code" : "A07044","name" : "필름밴드"},                                          
{"key" : "A07","code" : "A07045","name" : "헤리컬밴드"},                                        
{"key" : "A07","code" : "A07047","name" : "PVC 전선관"},                                        
{"key" : "A01","code" : "A01001","name" : "1X16 DWDM Multiplexer"},                             
{"key" : "A01","code" : "A01003","name" : "1X2 DWDM Mux.(ONU용)"},                              
{"key" : "A01","code" : "A01005","name" : "1X4 DWDM Mux.(ONU용)"},                              
{"key" : "A01","code" : "A01007","name" : "광감쇄기(ONU)"},                                     
{"key" : "A01","code" : "A01009","name" : "광증폭기"},                                          
{"key" : "A01","code" : "A01010","name" : "동축모듈"},                                          
{"key" : "A01","code" : "A01012","name" : "망감시기(인터페이스 모듈)"},                         
{"key" : "A01","code" : "A01014","name" : "상향광송신기"},                                      
{"key" : "A01","code" : "A01016","name" : "상향분할보드"},                                      
{"key" : "A01","code" : "A01018","name" : "적재함"},                                            
{"key" : "A01","code" : "A01019","name" : "전원공급기"},                                        
{"key" : "A01","code" : "A01021","name" : "프리앰프"},                                          
{"key" : "A01","code" : "A01024","name" : "하향분할보드"},                                      
{"key" : "A08","code" : "A08001","name" : "동축감쇄기 "},                                       
{"key" : "A08","code" : "A08002","name" : "필터 LOCK KEY "},                                    
{"key" : "A08","code" : "A08005","name" : "LOCK PIPE "},                                        
{"key" : "A08","code" : "A08007","name" : "MA/CA 결합기 "},                                     
{"key" : "A09","code" : "A09001","name" : "광접속함체(여장)"},                                  
{"key" : "A09","code" : "A09002","name" : "TRAY"},                                              
{"key" : "A09","code" : "A09003","name" : "광접속함체 케이스"},                                 
{"key" : "A09","code" : "A09004","name" : "열수축슬리브"},                                      
{"key" : "A09","code" : "A09005","name" : "광분기기함"},                                        
{"key" : "A09","code" : "A09006","name" : "광분배함(OFD함)"},                                   
{"key" : "A09","code" : "A09008","name" : "스터브케이블"},                                      
{"key" : "A09","code" : "A09009","name" : "디스트리뷰션 케이블"},                               
{"key" : "A09","code" : "A09010","name" : "엔트리커넥터"},                                      
{"key" : "A09","code" : "A09011","name" : "광커플러"},                                          
{"key" : "A09","code" : "A09012","name" : "광피그테일"},                                        
{"key" : "A09","code" : "A09013","name" : "광점퍼코드(Single Mode)"},                           
{"key" : "A09","code" : "A09014","name" : "광점퍼코드(Multi Duel Mode)"},                       
{"key" : "A09","code" : "A09015","name" : "광점퍼코드(Duel Mode)"},                             
{"key" : "A09","code" : "A09016","name" : "멀티점퍼코드"},                                      
{"key" : "A09","code" : "A09017","name" : "광아답터"},                                          
{"key" : "A09","code" : "A09018","name" : "광감쇄기"},                                          
{"key" : "A07","code" : "A07051","name" : "바인딩 작업"},                                       
{"key" : "A06","code" : "A06013","name" : "옥내용수동소자 작업"},                               
{"key" : "A06","code" : "A06014","name" : "2차탭 설치"},                                        
{"key" : "A02","code" : "A02016","name" : "구내증폭기 시험"},                                   
{"key" : "A02","code" : "A02017","name" : "간선증폭기 시험"},                                   
{"key" : "A02","code" : "A02018","name" : "연장증폭기 시험"},                                   
{"key" : "A01","code" : "A01048","name" : "ONU 시험"},                                          
{"key" : "A07","code" : "A07052","name" : "중전선 접지"},                                       
{"key" : "A07","code" : "A07053","name" : "접지(가공)"},                                        
{"key" : "A07","code" : "A07054","name" : "접지(지하)"},                                        
{"key" : "A07","code" : "A07056","name" : "전원케이블 시설"},                                   
{"key" : "A07","code" : "A07059","name" : "장치함"},                                            
{"key" : "A04","code" : "A04004","name" : "광케이블 작업"},                                     
{"key" : "A04","code" : "A04005","name" : "케이블 작업"},                                       
{"key" : "C01","code" : "C01001","name" : "리모컨"},                                            
{"key" : "C01","code" : "C01002","name" : "A/V케이블"},                                         
{"key" : "B10","code" : "B10001","name" : "케이블모뎀"},                                        
{"key" : "B10","code" : "B10002","name" : "랜 케이블 (1,500mm)"},                               
{"key" : "B10","code" : "B10003","name" : "아답터 (12V 1A)"},                                   
{"key" : "B10","code" : "B10004","name" : "아답터 (9V 1.2A)"},                                  
{"key" : "B10","code" : "B10005","name" : "아답터 (9V 1A/9V 850mA)"},                           
{"key" : "B10","code" : "B10006","name" : "랜 카드"},                                           
{"key" : "B10","code" : "B10007","name" : "무선 모뎀"},                                         
{"key" : "B05","code" : "B05015","name" : "L3 24port Giga"},                                    
{"key" : "B05","code" : "B05016","name" : "L3 16port Giga"},                                    
{"key" : "D01","code" : "D01001","name" : "PC"},                                                
{"key" : "B05","code" : "B05018","name" : "L3 16port FX"},                                      
{"key" : "B05","code" : "B05019","name" : "L3 24port FX"},                                      
{"key" : "B05","code" : "B05020","name" : "L3 24port TX"},                                      
{"key" : "B05","code" : "B05021","name" : "L2 24port TX"},                                      
{"key" : "B05","code" : "B05022","name" : "V D S L"},                                           
{"key" : "B05","code" : "B05023","name" : "GBIC"},                                              
{"key" : "B01","code" : "B01001","name" : "UBR10012"},                                          
{"key" : "B01","code" : "B01002","name" : "UBR7246VXR"},                                        
{"key" : "B02","code" : "B02001","name" : "OSR-7609"},                                          
{"key" : "B02","code" : "B02002","name" : "Catalyst-6500"},                                     
{"key" : "B02","code" : "B02003","name" : "6500/7600용 라인카드"},                              
{"key" : "B02","code" : "B02004","name" : "Catalyst-4507R"},                                    
{"key" : "B02","code" : "B02005","name" : "Catalyst-3750"},                                     
{"key" : "B02","code" : "B02006","name" : "Catalyst-3550"},                                     
{"key" : "B02","code" : "B02007","name" : "Cisco GBIC모듈"},                                    
{"key" : "B04","code" : "B04001","name" : "SUN서버"},                                           
{"key" : "C02","code" : "C02001","name" : "Set-Top Box"},                                       
{"key" : "C02","code" : "C02002","name" : "Middleware"},                                        
{"key" : "C02","code" : "C02003","name" : "EPG, SUN JVM"},                                      
{"key" : "C02","code" : "C02005","name" : "Card"},                                              
{"key" : "C02","code" : "C02006","name" : "리모컨"},                                            
{"key" : "B07","code" : "B07001","name" : "집선장비"},                                          
{"key" : "B07","code" : "B07002","name" : "모뎀"},                                              
{"key" : "B11","code" : "B11001","name" : "VoIP Access Gateway Shelf"},                         
{"key" : "B11","code" : "B11002","name" : "VoIP Access Gateway 8port Module"},                  
{"key" : "B11","code" : "B11003","name" : "VoIP Trunk Gateway Shelf"},                          
{"key" : "C05","code" : "C05159","name" : "MCP-2202-F01"},                                      
{"key" : "C05","code" : "C05161","name" : "Video Processor"},                                   
{"key" : "C05","code" : "C05162","name" : "Decoder"},                                           
{"key" : "C05","code" : "C05167","name" : "Modula and M/V System"},                             
{"key" : "C05","code" : "C05169","name" : "HD CG System"},                                      
{"key" : "C05","code" : "C05173","name" : "지역채널 송출 HD 전환 SI"},                          
{"key" : "C05","code" : "C05174","name" : "WS-C2560X-48T-S"},                                   
{"key" : "C05","code" : "C05175","name" : "GLC-SX-MM"},                                         
{"key" : "C05","code" : "C05176","name" : "Cable 공사"},                                        
{"key" : "C14","code" : "C14013","name" : "비선형편집기"},                                      
{"key" : "C15","code" : "C15048","name" : "비선형편집기"},                                      
{"key" : "B17","code" : "B17004","name" : "QoS Switch"},                                        
{"key" : "A09","code" : "A09037","name" : "크로스탭"},                                          
{"key" : "A05","code" : "A05007","name" : "UPS모듈 (AS용)"},                                    
{"key" : "C15","code" : "C15049","name" : "보도정보시스템 지역센터 시스템 구축(abc)"},          
{"key" : "C15","code" : "C15051","name" : "보도정보시스템 비디오서버 및 Storage(Omneon)(abc)"}, 
{"key" : "C15","code" : "C15052","name" : "보도정보시스템 아카이브 연동 추가 부분 개발(abc)"},  
{"key" : "C15","code" : "C15055","name" : "보도정보시스템 Network(백본스위치 10G 추가)(중부)"}, 
{"key" : "C15","code" : "C15056","name" : "보도정보시스템 비디오서버(Omneon)(낙동)"},           
{"key" : "C15","code" : "C15059","name" : "보도정보시스템 조명시스템(abc)"},                    
{"key" : "C15","code" : "C15064","name" : "보도정보시스템 자막시스템"},                         
{"key" : "C15","code" : "C15065","name" : "보도정보시스템 계측기(abc)"},                        
{"key" : "C15","code" : "C15066","name" : "보도정보시스템 계측기(중부, 낙동)"},                 
{"key" : "C15","code" : "C15067","name" : "보도정보시스템 비디오시스템(abc)"},                  
{"key" : "C15","code" : "C15068","name" : "보도정보시스템 오디오시스템(abc)"},                  
{"key" : "C15","code" : "C15069","name" : "보도정보시스템 마이크시스템(abc)"},                  
{"key" : "C15","code" : "C15070","name" : "보도정보시스템 인터컴시스템(abc)"},                  
{"key" : "C15","code" : "C15072","name" : "보도정보시스템(VDA)(abc)"},                          
{"key" : "C15","code" : "C15073","name" : "보도정보시스템 Wideband Router(abc)"},               
{"key" : "C15","code" : "C15075","name" : "보도정보시스템 Special Made Prodect(abc)"},          
{"key" : "C15","code" : "C15076","name" : "보도정보시스템 스튜디오카메라(abc)"},                
{"key" : "C15","code" : "C15077","name" : "보도정보시스템 VCR(abc)"},                           
{"key" : "C15","code" : "C15078","name" : "보도정보시스템 비디오시스템(중부, 낙동)"},           
{"key" : "C15","code" : "C15080","name" : "보도정보시스템 인터컴시스템(중부, 낙동)"},           
{"key" : "C15","code" : "C15083","name" : "보도정보시스템 모니터시스템(중부, 낙동)"},           
{"key" : "C15","code" : "C15084","name" : "보도정보시스템 Wideband Router(중부, 낙동)"},        
{"key" : "C15","code" : "C15085","name" : "보도정보시스템 IP코덱 시스템(중부, 낙동)"},          
{"key" : "C15","code" : "C15087","name" : "보도정보시스템 Special Made Product(중부, 낙동)"},   
{"key" : "C15","code" : "C15090","name" : "보도정보시스템 스튜디오카메라(낙동)"},               
{"key" : "C15","code" : "C15091","name" : "보도정보시스템 비디오카메라(낙동)"},                 
{"key" : "C05","code" : "C05178","name" : "장애인방송C.Caption On-Air(중부,전주,대구,낙동)"},   
{"key" : "C05","code" : "C05180","name" : "장애인방송C.Caption Editor(중부,전주,대구,낙동)"},   
{"key" : "C05","code" : "C05181","name" : "장애인방송Multi Serial Modulator(수원)"},            
{"key" : "C05","code" : "C05182","name" : "장애인방송C.Caption Inserter(중부,전주,대구,낙동)"}, 
{"key" : "C06","code" : "C06011","name" : "인천 제작센터 이전 공사"},                           
{"key" : "A09","code" : "A09038","name" : "광접속함체(RN포함)"},                                
{"key" : "B05","code" : "B05042","name" : "L2 16Port TX"},                                      
{"key" : "C14","code" : "C14014","name" : "교통방송 시스템 이전에 따른 설비 구축"},             
{"key" : "E01","code" : "E01041","name" : "시청채널 정보 제공 기능 개발"},                      
{"key" : "B04","code" : "B04015","name" : "네트워크 관리시스템(NMS)성능 개선"},                 
{"key" : "C04","code" : "C04078","name" : "L2 Switch, Module"},                                 
{"key" : "C15","code" : "C15095","name" : "보안강화"},                                          
{"key" : "C15","code" : "C15096","name" : "보도정보복구"},                                      
{"key" : "C15","code" : "C15097","name" : "보도정보시스템(새롬)"},                              
{"key" : "C15","code" : "C15098","name" : "HD Studio Camera(새롬)"},                            
{"key" : "C15","code" : "C15101","name" : "File Recoder(서해)"},                                
{"key" : "C15","code" : "C15100","name" : "4K,HD Dual System(서해)"},                           
{"key" : "C15","code" : "C15106","name" : "Prompter(남동)"},                                    
{"key" : "C15","code" : "C15107","name" : "Install Materials(남동)"},                           
{"key" : "C04","code" : "C04080","name" : "License"},                                           
{"key" : "C04","code" : "C04083","name" : "대용량 스토리지 배터리"},                            
{"key" : "C11","code" : "C11010","name" : "FMS(환경감시시스템)"},                               
{"key" : "C05","code" : "C05183","name" : "Video Sever"},                                       
{"key" : "C05","code" : "C05184","name" : "IP Enc/Dec"},                                        
{"key" : "C05","code" : "C05185","name" : "Routing Switcher"},                                  
{"key" : "C05","code" : "C05186","name" : "System Rack"},                                       
{"key" : "C05","code" : "C05188","name" : "지역CH 케이블링/환경공사"},                          
{"key" : "C05","code" : "C05189","name" : "지역CH 이전설치"},                                   
{"key" : "C05","code" : "C05190","name" : "WS-X6748-GE-TX"},                                    
{"key" : "C05","code" : "C05191","name" : "CG"},                                                
{"key" : "C05","code" : "C05192","name" : "APC"},                                               
{"key" : "C15","code" : "C15110","name" : "데스크탑"},                                          
{"key" : "C14","code" : "C14015","name" : "노트북"},                                            
{"key" : "C04","code" : "C04084","name" : "Wall Monitoring System"},                            
{"key" : "C04","code" : "C04086","name" : "Consol Desk"},                                       
{"key" : "C04","code" : "C04088","name" : "FMS"},                                               
{"key" : "C04","code" : "C04090","name" : "통합관제시스템"},                                    
{"key" : "B11","code" : "B11023","name" : "씨엔티테크"},                                        
{"key" : "A07","code" : "A07073","name" : "장력이탈밴드"},                                      
{"key" : "[01","code" : "[01001","name" : "USIM"},                                              
{"key" : "C14","code" : "C14012","name" : "Studio Tripod"},                                     
{"key" : "C05","code" : "C05172","name" : "케이블 설치 공사"},                                  
{"key" : "E01","code" : "E01040","name" : "티브로드 지역채널 앱 기능 추가"},                    
{"key" : "B04","code" : "B04016","name" : "단말기 실사용 여부 점검 시스템"},                    
{"key" : "C15","code" : "C15105","name" : "Monitoring System(남동)"},                           
{"key" : "C02","code" : "C02010","name" : "휴맥스 STB 아답터"},                                 
{"key" : "C15","code" : "C15103","name" : "Video 분배설비(남동)"},                              
{"key" : "B04","code" : "B04017","name" : "서비스 장비 접속인증시스템"},                        
{"key" : "B02","code" : "B02019","name" : "Catalyst-3945"},                                     
{"key" : "C15","code" : "C15109","name" : "노트북"},                                            
{"key" : "C04","code" : "C04089","name" : "항온항습기"},                                        
{"key" : "B11","code" : "B11018","name" : "운서동 더레지던스호텔"},                             
{"key" : "C05","code" : "C05156","name" : "MDM-5501"},                                          
{"key" : "C05","code" : "C05155","name" : "MDM-5321"},                                          
{"key" : "C05","code" : "C05163","name" : "NCOMPASS Control System"},                           
{"key" : "C05","code" : "C05165","name" : "Decoder-1"},                                         
{"key" : "C05","code" : "C05168","name" : "ACL System"},                                        
{"key" : "C05","code" : "C05171","name" : "하단 자막 업그레이드"},                              
{"key" : "C15","code" : "C15050","name" : "보도정보시스템 네트워크 S/W, 방화벽(VPN)(abc)"},     
{"key" : "C15","code" : "C15053","name" : "보도정보시스템 비디오서버(Omneon)(중부)"},           
{"key" : "C15","code" : "C15054","name" : "보도정보시스템 Storage(Omneon)(중부)"},              
{"key" : "C15","code" : "C15061","name" : "보도정보시스템 조명시스템(낙동)"},                   
{"key" : "C15","code" : "C15063","name" : "보도정보시스템 비디오스위쳐(중부, 낙동)"},           
{"key" : "C15","code" : "C15074","name" : "보도정보시스템 Installation Materials(abc)"},        
{"key" : "C15","code" : "C15089","name" : "보도정보시스템 비디오카메라(중부)"},                 
{"key" : "C15","code" : "C15094","name" : "ABC 공조설비 노후 교체"},                            
{"key" : "C15","code" : "C15093","name" : "보도정보시스템 비디오스위쳐(abc)"},                  
{"key" : "C15","code" : "C15102","name" : "C/G(남동)"},                                         
{"key" : "C04","code" : "C04079","name" : "H/W"},                                               
{"key" : "C15","code" : "C15099","name" : "HD ENG Camera(새롬)"},                               
{"key" : "C04","code" : "C04081","name" : "개발비"},                                            
{"key" : "C04","code" : "C04082","name" : "지상파 VOD 홀드백 시간단축 개발"},                   
{"key" : "C14","code" : "C14016","name" : "데스크탑"},                                          
{"key" : "B11","code" : "B11019","name" : "부일로지스 IPT"},                                    
{"key" : "B02","code" : "B02018","name" : "속도측정시스템"},                                    
{"key" : "C05","code" : "C05160","name" : "MIP-5321"},                                          
{"key" : "C05","code" : "C05164","name" : "Video Processor-1"},                                 
{"key" : "C05","code" : "C05166","name" : "F/S and Up Convertor"},                              
{"key" : "C05","code" : "C05170","name" : "HD CG Upgrade"},                                     
{"key" : "C14","code" : "C14011","name" : "ENG Tripod"},                                        
{"key" : "[02","code" : "[02001","name" : "MVNO용 Cellular Phone"},                             
{"key" : "C15","code" : "C15057","name" : "보도정보시스템 Storage(Omneon)(낙동)"},              
{"key" : "C15","code" : "C15058","name" : "보도정보시스템 Network(백본스위치 10Gb 추가)(낙동)"},
{"key" : "C15","code" : "C15060","name" : "보도정보시스템 조명시스템(중부)"},                   
{"key" : "C15","code" : "C15062","name" : "보도정보시스템 오디오시스템(중부, 낙동)"},           
{"key" : "C15","code" : "C15071","name" : "보도정보시스템 모니터시스템(abc)"},                  
{"key" : "C15","code" : "C15079","name" : "보도정보시스템 마이크시스템(중부, 낙동)"},           
{"key" : "C15","code" : "C15081","name" : "보도정보시스템 VDA(중부, 낙동)"},                    
{"key" : "C15","code" : "C15082","name" : "보도정보시스템 NLE System(중부, 낙동)"},             
{"key" : "C15","code" : "C15086","name" : "보도정보시스템 Installation Materials(중부, 낙동)"}, 
{"key" : "C15","code" : "C15088","name" : "보도정보시스템 스튜디오카메라(중부)"},               
{"key" : "C15","code" : "C15092","name" : "보도정보시스템 VCR(중부, 낙동)"},                    
{"key" : "C05","code" : "C05177","name" : "장애인방송C.Caption On-Air(수원)"},                  
{"key" : "C05","code" : "C05179","name" : "장애인방송C.Caption Editor(수원)"},                  
{"key" : "C15","code" : "C15104","name" : "비선형 편집기(남동)"},                               
{"key" : "C05","code" : "C05187","name" : "ACO"},                                               
{"key" : "C15","code" : "C15108","name" : "ENG Camera"},                                        
{"key" : "C04","code" : "C04087","name" : "멀티뷰어"},                                          
{"key" : "B11","code" : "B11022","name" : "모두스테이 스타즈호텔"},                             
{"key" : "C04","code" : "C04009","name" : "VOD Server"},                                        
{"key" : "B01","code" : "B01011","name" : "Edge-QAM"},                                          
{"key" : "B10","code" : "B10010","name" : "Arris 케이블 모뎀"},                                 
{"key" : "B01","code" : "B01012","name" : "RF-Switch"},                                         
{"key" : "B11","code" : "B11005","name" : "VoIP Home Gateway(MTA)"},                            
{"key" : "A12","code" : "A12052","name" : "PDA"},                                               
{"key" : "A07","code" : "A07069","name" : "CD관"},                                              
{"key" : "C04","code" : "C04010","name" : "Digital Remodulator"},                               
{"key" : "B11","code" : "B11006","name" : "VoIP Phone(IP Phone)"},                              
{"key" : "A07","code" : "A07070","name" : "J형 브라켓"},                                        
{"key" : "D01","code" : "D01022","name" : "DDR2 1GB"},                                          
{"key" : "A01","code" : "A01054","name" : "WDM DMUX"},                                          
{"key" : "D01","code" : "D01023","name" : "Server(NOC용)"},                                     
{"key" : "A01","code" : "A01053","name" : "WDM MUX"},                                           
{"key" : "C05","code" : "C05027","name" : "Digital 전용 광 송수긴기"},                          
{"key" : "C05","code" : "C05028","name" : "All Format Vodeo Concerter"},                        
{"key" : "C05","code" : "C05029","name" : "Multi Keyer-Power Supply"},                          
{"key" : "B12","code" : "B12010","name" : "SMC-100(MM)"},                                       
{"key" : "B12","code" : "B12011","name" : "CS-SMC-2(SM)"},                                      
{"key" : "B12","code" : "B12012","name" : "CS-SMC-1(SM)"},                                      
{"key" : "B11","code" : "B11007","name" : "VoIP Voice over Cable Modem(VoCM)"},                 
{"key" : "C04","code" : "C04011","name" : "HD H/E System"},                                     
{"key" : "B05","code" : "B05031","name" : "GE-PON(OLT L3)"},                                    
{"key" : "B05","code" : "B05032","name" : "ONT"},                                               
{"key" : "C15","code" : "C15009","name" : "Prompter"},                                          
{"key" : "D04","code" : "D04003","name" : "PDA"},                                               
{"key" : "B16","code" : "B16001","name" : "FMS"},                                               
{"key" : "B16","code" : "B16002","name" : "원격 콘솔 제어 시스템"},                             
{"key" : "E01","code" : "E01039","name" : "Netclinic"},                                         
{"key" : "C11","code" : "C11004","name" : "발전기 차량"},                                       
{"key" : "C11","code" : "C11005","name" : "전기공사(기타)자재"},                                
{"key" : "B05","code" : "B05033","name" : "L3-S5500-28F Chassis"},                              
{"key" : "B05","code" : "B05034","name" : "L2-SI2024SF Chassis"},                               
{"key" : "B05","code" : "B05035","name" : "L2-SI2024ST Chassis"},                               
{"key" : "B05","code" : "B05036","name" : "L2-SI214FT Chassis"},                                
{"key" : "B05","code" : "B05037","name" : "L3-S5500-28F Optional Module"},                      
{"key" : "B05","code" : "B05038","name" : "L2-SI2024SF Optional Module"},                       
{"key" : "B05","code" : "B05039","name" : "L2-SI2024ST Optional Module"},                       
{"key" : "A09","code" : "A09031","name" : "광점퍼코드(Multi Mode)"},                            
{"key" : "A09","code" : "A09032","name" : "광점퍼코드(Single Dual Mode)"},                      
{"key" : "A12","code" : "A12053","name" : "상향측정봉"},                                        
{"key" : "A02","code" : "A02026","name" : "하향등화기(엔씨)"},                                  
{"key" : "A02","code" : "A02027","name" : "하향역등화기(엔씨)"},                                
{"key" : "A02","code" : "A02028","name" : "상향등화기(엔씨)"},                                  
{"key" : "A05","code" : "A05005","name" : "자동복구기"},                                        
{"key" : "B05","code" : "B05040","name" : "L2 24port FX"},                                      
{"key" : "A11","code" : "A11032","name" : "전원 케이블포설"},                                   
{"key" : "A11","code" : "A11033","name" : "장치함 작업"},                                       
{"key" : "C11","code" : "C11006","name" : "수배전반"},                                          
{"key" : "C12","code" : "C12006","name" : "전열교환기"},                                        
{"key" : "C11","code" : "C11007","name" : "발전차량 내장탑"},                                   
{"key" : "B11","code" : "B11008","name" : "Server(SW)"},                                        
{"key" : "B17","code" : "B17001","name" : "QoS 장비(Hardware)"},                                
{"key" : "B17","code" : "B17002","name" : "QoS Server"},                                        
{"key" : "B17","code" : "B17003","name" : "QoS Software"},                                      
{"key" : "B11","code" : "B11009","name" : "IP-PBX"},                                            
{"key" : "B02","code" : "B02013","name" : "Cisco CRS 모듈"},                                    
{"key" : "B02","code" : "B02014","name" : "Foundry 10G Switching Router"},                      
{"key" : "B04","code" : "B04004","name" : "소프트웨어"},                                        
{"key" : "A09","code" : "A09033","name" : "광접속함체(직선형)"},                                
{"key" : "B18","code" : "B18001","name" : "전원장비"},                                          
{"key" : "A01","code" : "A01055","name" : "CCTV 분할보드"},                                     
{"key" : "B19","code" : "B19001","name" : "VPN(Virtual Private Network) Systems"},              
{"key" : "B04","code" : "B04005","name" : "DNS Server"},                                        
{"key" : "A06","code" : "A06016","name" : "지중용 TAP- OFF"},                                   
{"key" : "C13","code" : "C13001","name" : "인테리어"},                                          
{"key" : "C12","code" : "C12007","name" : "DUCT"},                                              
{"key" : "C04","code" : "C04012","name" : "Digital 수신설비"},                                  
{"key" : "A02","code" : "A02029","name" : "감쇄기(엔씨)"},                                      
{"key" : "C14","code" : "C14005","name" : "SONY Z1 Full Set"},                                  
{"key" : "A04","code" : "A04006","name" : "ABF 케이블"},                                        
{"key" : "A09","code" : "A09034","name" : "ABF광커넥터"},                                       
{"key" : "A09","code" : "A09035","name" : "ABF 분기기"},                                        
{"key" : "B04","code" : "B04006","name" : "Dell Server"},                                       
{"key" : "A12","code" : "A12054","name" : "광절단기"},                                          
{"key" : "A12","code" : "A12055","name" : "광검출기"},                                          
{"key" : "A12","code" : "A12056","name" : "커넥터 드라이버"},                                   
{"key" : "A01","code" : "A01056","name" : "감쇄기(PAD)"},                                       
{"key" : "B10","code" : "B10011","name" : "Docsis 3.0 SA Modem (TI Chip)- DPC3000"},            
{"key" : "B10","code" : "B10012","name" : "Motorola SB6120E (DOCSIS 3.0 TI CHIP)"},             
{"key" : "B04","code" : "B04007","name" : "속도측정시스템"},                                    
{"key" : "B11","code" : "B11010","name" : "VoIP용 UPS"},                                        
{"key" : "B11","code" : "B11011","name" : "Wi-Fi Phone"},                                       
{"key" : "C04","code" : "C04013","name" : "Re-encording System"},                               
{"key" : "B05","code" : "B05041","name" : "L3 48Port Giga"},                                    
{"key" : "A05","code" : "A05006","name" : "망감시모듈"},                                        
{"key" : "A12","code" : "A12057","name" : "휴대용계측장비"},                                    
{"key" : "B12","code" : "B12013","name" : "집합형하우징(18슬롯)"},                              
{"key" : "B12","code" : "B12014","name" : "전원공급기"},                                        
{"key" : "B12","code" : "B12015","name" : "망감시모듈"},                                        
{"key" : "B12","code" : "B12016","name" : "집합형 미디어컨버터(1Core)"},                        
{"key" : "B12","code" : "B12017","name" : "단독형 미디어컨버터(1Core)"},                        
{"key" : "B12","code" : "B12018","name" : "집합형미디어컨버터(멀티모드)"},                      
{"key" : "B12","code" : "B12019","name" : "단독형 미디어컨버터(멀티모드)"},                     
{"key" : "A07","code" : "A07071","name" : "PVC 함체"},                                          
{"key" : "A12","code" : "A12058","name" : "공구세트"},                                          
{"key" : "C11","code" : "C11008","name" : "STS"},                                               
{"key" : "C11","code" : "C11009","name" : "NMS"},                                               
{"key" : "C04","code" : "C04014","name" : "국산 XCAS시스템 구축"},                              
{"key" : "C04","code" : "C04015","name" : "DMC통합"},                                           
{"key" : "C04","code" : "C04016","name" : "IP Encoder"},                                        
{"key" : "C04","code" : "C04017","name" : "IP Decoder"},                                        
{"key" : "B10","code" : "B10013","name" : "Wideband Modem"},                                    
{"key" : "C06","code" : "C06008","name" : "Studio 인테리어"},                                   
{"key" : "C06","code" : "C06009","name" : "Studio 조명"},                                       
{"key" : "C15","code" : "C15010","name" : "IP Decorder"},                                       
{"key" : "C15","code" : "C15011","name" : "IP Encorder"},                                       
{"key" : "A11","code" : "A11034","name" : "외벽로프작업"},                                      
{"key" : "A11","code" : "A11035","name" : "방화폼설치작업"},                                    
{"key" : "A12","code" : "A12059","name" : "자동절체기"},                                        
{"key" : "C02","code" : "C02008","name" : "X-CAS Royalty"},                                     
{"key" : "C15","code" : "C15013","name" : "변조기"},                                            
{"key" : "A14","code" : "A14001","name" : "기타"},                                              
{"key" : "C15","code" : "C15012","name" : "L3 Switch"},                                         
{"key" : "C15","code" : "C15014","name" : "VDA"},                                               
{"key" : "C15","code" : "C15015","name" : "ADA"},                                               
{"key" : "C15","code" : "C15016","name" : "디지털TV"},                                          
{"key" : "C15","code" : "C15017","name" : "E5710"},                                             
{"key" : "C15","code" : "C15018","name" : "RX8200"},                                            
{"key" : "C15","code" : "C15019","name" : "일기예보 프로그램"},                                 
{"key" : "C04","code" : "C04018","name" : "Backbone Switch"},                                   
{"key" : "A02","code" : "A02030","name" : "감쇄기(동양-구내)"},                                 
{"key" : "A02","code" : "A02031","name" : "상향등화기(동양-구내)"},                             
{"key" : "C04","code" : "C04019","name" : "Nagravision CAS License (100Ch)"},                   
{"key" : "A13","code" : "A13005","name" : "위성 수신기"},                                       
{"key" : "C15","code" : "C15020","name" : "개표방송 프로그램"},                                 
{"key" : "C09","code" : "C09003","name" : "디지털 전용 양방향 송수신기(60Km)"},                 
{"key" : "C09","code" : "C09004","name" : "Rack Mount"},                                        
{"key" : "C09","code" : "C09005","name" : "BrightEye 46"},                                      
{"key" : "C09","code" : "C09006","name" : "BrightEye 48"},                                      
{"key" : "C09","code" : "C09007","name" : "BrightEye 24"},                                      
{"key" : "C09","code" : "C09008","name" : "Rack Mount -1"},                                     
{"key" : "C09","code" : "C09009","name" : "광 점퍼코드(기본 3m/2core)"},                        
{"key" : "C16","code" : "C16004","name" : "WIRELESS MIC SYSTEM(ULXP SERIES)"},                  
{"key" : "C16","code" : "C16005","name" : "ANTENNA(UA870WB)"},                                  
{"key" : "C16","code" : "C16006","name" : "DISTRIBUTER(UA844SWB-K)"},                           
{"key" : "C16","code" : "C16007","name" : "CONDENCER PIN MIC (MC50B)"},                         
{"key" : "A12","code" : "A12060","name" : "기타구매"},                                          
{"key" : "B04","code" : "B04008","name" : "악성 코드 감염 PC 치료 체계"},                       
{"key" : "C03","code" : "C03005","name" : "자동오디오 제어기"},                                 
{"key" : "C03","code" : "C03006","name" : "아날로그 광고삽입기"},                               
{"key" : "C04","code" : "C04020","name" : "디지털신호처리기"},                                  
{"key" : "B10","code" : "B10014","name" : "Hitron Docsis 3.0(TI Chip)"},                        
{"key" : "C05","code" : "C05030","name" : "비디오서버(큐릭스)"},                                
{"key" : "C05","code" : "C05031","name" : "비디오서버(강서,동대문,새롬,서해)"},                 
{"key" : "C05","code" : "C05032","name" : "비디오서버(한빛,ABC,남동,기남)"},                    
{"key" : "C05","code" : "C05033","name" : "비디오서버(수원)"},                                  
{"key" : "C05","code" : "C05035","name" : "비디오서버(중부)"},                                  
{"key" : "C05","code" : "C05036","name" : "비디오서버(전주,대구,낙동)"},                        
{"key" : "B10","code" : "B10015","name" : "광랜"},                                              
{"key" : "B11","code" : "B11012","name" : "Wi-Fi AP"},                                          
{"key" : "C05","code" : "C05037","name" : "CG(큐릭스)"},                                        
{"key" : "C05","code" : "C05038","name" : "CG(강서,동대문,새롬,서해)"},                         
{"key" : "C05","code" : "C05039","name" : "CG(한빛,ABC,남동,기남)"},                            
{"key" : "C05","code" : "C05040","name" : "CG(수원)"},                                          
{"key" : "C05","code" : "C05042","name" : "CG(중부)"},                                          
{"key" : "C05","code" : "C05043","name" : "CG(전주,대구,낙동)"},                                
{"key" : "C05","code" : "C05044","name" : "Keyer(큐릭스)"},                                     
{"key" : "C05","code" : "C05045","name" : "Keyer(강서,동대문,새롬,서해)"},                      
{"key" : "C05","code" : "C05046","name" : "Keyer(한빛,ABC,남동,기남)"},                         
{"key" : "C05","code" : "C05047","name" : "Keyer(수원)"},                                       
{"key" : "C05","code" : "C05049","name" : "Keyer(중부)"},                                       
{"key" : "C05","code" : "C05050","name" : "Keyer(전주,대구,낙동)"},                             
{"key" : "C05","code" : "C05051","name" : "APC S/W(큐릭스)"},                                   
{"key" : "C05","code" : "C05052","name" : "APC S/W(강서,동대문,새롬,서해)"},                    
{"key" : "C05","code" : "C05053","name" : "APC S/W(한빛,ABC,남동,기남)"},                       
{"key" : "C05","code" : "C05054","name" : "APC S/W(수원)"},                                     
{"key" : "C05","code" : "C05056","name" : "APC S/W(중부)"},                                     
{"key" : "C05","code" : "C05057","name" : "APC S/W(전주,대구,낙동)"},                           
{"key" : "C05","code" : "C05058","name" : "CMS Main 스토리지(큐릭스)"},                         
{"key" : "C05","code" : "C05059","name" : "CMS Main 스토리지(강서,동대문,새롬,서해)"},          
{"key" : "C05","code" : "C05060","name" : "CMS Main 스토리지(한빛,ABC,남동,기남)"},             
{"key" : "C05","code" : "C05061","name" : "CMS Main 스토리지(수원)"},                           
{"key" : "C05","code" : "C05064","name" : "CMS Main 스토리지(중부)"},                           
{"key" : "C05","code" : "C05065","name" : "CMS Main 스토리지(전주,대구,낙동)"},                 
{"key" : "C05","code" : "C05066","name" : "CMS(큐릭스)"},                                       
{"key" : "C05","code" : "C05067","name" : "CMS(강서,동대문,새롬,서해)"},                        
{"key" : "C05","code" : "C05068","name" : "CMS(한빛,ABC,남동,기남)"},                           
{"key" : "C05","code" : "C05069","name" : "CMS(수원)"},                                         
{"key" : "C05","code" : "C05071","name" : "CMS(중부)"},                                         
{"key" : "C05","code" : "C05072","name" : "CMS(전주,대구,낙동)"},                               
{"key" : "C05","code" : "C05073","name" : "계측기(Tektronix)-큐릭스"},                          
{"key" : "C05","code" : "C05074","name" : "계측기(Tektronix)-강서,동대문,새롬,서해"},           
{"key" : "C05","code" : "C05075","name" : "계측기(Tektronix)-한빛,ABC,남동,기남"},              
{"key" : "C05","code" : "C05076","name" : "계측기(Tektronix)-수원"},                            
{"key" : "C04","code" : "C04021","name" : "Castanets eStream Server(H/W)"},                     
{"key" : "C05","code" : "C05078","name" : "계측기(Tektronix)-중부"},                            
{"key" : "C05","code" : "C05079","name" : "계측기(Tektronix)-전주,대구,낙동"},                  
{"key" : "C05","code" : "C05080","name" : "Syne Generator(큐릭스)"},                            
{"key" : "C05","code" : "C05081","name" : "Syne Generator(강서,동대문,새롬,서해)"},             
{"key" : "C05","code" : "C05082","name" : "Syne Generator(한빛,ABC,남동,기남)"},                
{"key" : "C05","code" : "C05083","name" : "Syne Generator(수원)"},                              
{"key" : "C05","code" : "C05085","name" : "Syne Generator(중부)"},                              
{"key" : "C05","code" : "C05086","name" : "Syne Generator(전주,대구,낙동)"},                    
{"key" : "C05","code" : "C05087","name" : "GPS Clock Generator(큐릭스)"},                       
{"key" : "C05","code" : "C05088","name" : "GPS Clock Generator(강서,동대문,새롬,서해)"},        
{"key" : "C05","code" : "C05089","name" : "GPS Clock Geneerator(한빛,ABC,남동,기남)"},          
{"key" : "C05","code" : "C05090","name" : "GPS Clock Generator(수원)"},                         
{"key" : "C05","code" : "C05092","name" : "GPS Clock Generator(중부)"},                         
{"key" : "C05","code" : "C05093","name" : "GPS Clock Generator(전주,대구,낙동)"},               
{"key" : "C05","code" : "C05094","name" : "모니터링(큐릭스)"},                                  
{"key" : "C05","code" : "C05095","name" : "모니터링(강서,동대문,새롬,서해)"},                   
{"key" : "C05","code" : "C05096","name" : "모니터링(한빛,ABC,남동,기남)"},                      
{"key" : "C05","code" : "C05097","name" : "모니터링(수원)"},                                    
{"key" : "C05","code" : "C05099","name" : "모니터링(중부)"},                                    
{"key" : "C05","code" : "C05100","name" : "모니터링(전주,대구,낙동)"},                          
{"key" : "C05","code" : "C05101","name" : "기타 Baseband 장비 -큐릭스"},                        
{"key" : "C05","code" : "C05102","name" : "기타 Baseband 장비 - 강서,동대문,새롬,서해"},        
{"key" : "C05","code" : "C05103","name" : "기타 Baseband 장비 - 한빛,ABC,남동,기남"},           
{"key" : "C05","code" : "C05104","name" : "기타 Baseband 장비 - 수원"},                         
{"key" : "C04","code" : "C04025","name" : "Castanets eStream Server(S/W) : 350Stream"},         
{"key" : "C05","code" : "C05106","name" : "기타 Baseband 장비 - 중부"},                         
{"key" : "C05","code" : "C05107","name" : "기타 Baseband 장비 - 전주,대구,낙동"},               
{"key" : "C05","code" : "C05108","name" : "IP Encoder/Decoder-큐릭스"},                         
{"key" : "C05","code" : "C05109","name" : "IP Encoder/Decoder-강서,동대문,새롬,서해"},          
{"key" : "C05","code" : "C05110","name" : "IP Encoder/Decoder-한빛ABC,남동,기남"},              
{"key" : "C05","code" : "C05111","name" : "IP Encoder/Decoder-수원"},                           
{"key" : "C05","code" : "C05113","name" : "IP Encoder/Decoder-중부"},                           
{"key" : "C05","code" : "C05114","name" : "IP Encoder/Decoder-전주,대구,낙동"},                 
{"key" : "C05","code" : "C05115","name" : "Modular-큐릭스"},                                    
{"key" : "C05","code" : "C05116","name" : "Modular-강서,동대문,새롬,서해"},                     
{"key" : "C05","code" : "C05117","name" : "Modular-한빛,ABC,남동,기남"},                        
{"key" : "C05","code" : "C05118","name" : "Modular-수원"},                                      
{"key" : "C04","code" : "C04027","name" : "Sanique Cluster File System(SAN 공유솔루션)"},       
{"key" : "C05","code" : "C05120","name" : "Modular-중부"},                                      
{"key" : "C05","code" : "C05121","name" : "Modular-전주,대구,낙동"},                            
{"key" : "C05","code" : "C05122","name" : "지역CH Network 장비-큐릭스"},                        
{"key" : "C05","code" : "C05123","name" : "지역CH Network 장비-강서,동대문,새롬,서해"},         
{"key" : "C05","code" : "C05124","name" : "지역CH Network 장비-한빛,ABC,남동,기남"},            
{"key" : "C05","code" : "C05125","name" : "지역CH Network 장비-수원"},                          
{"key" : "C04","code" : "C04028","name" : "LSM(Local Service Management) H/W"},                 
{"key" : "C05","code" : "C05127","name" : "지역CH Network 장비-중부"},                          
{"key" : "C05","code" : "C05128","name" : "지역CH Network 장비-전주,대구,낙동"},                
{"key" : "C05","code" : "C05129","name" : "지역CH 케이블링/환경공사-큐릭스"},                   
{"key" : "C05","code" : "C05130","name" : "지역CH 케이블링/환경공사-강서,동대문,새롬,서해"},    
{"key" : "C05","code" : "C05131","name" : "지역CH 케이블링/환경공사-한빛,ABC남동,기남"},        
{"key" : "C05","code" : "C05132","name" : "지역CH 케이블링/환경공사-수원"},                     
{"key" : "C04","code" : "C04029","name" : "VOD Storage 6,000시간"},                             
{"key" : "C05","code" : "C05134","name" : "지역CH 케이블링/환경공사-중부"},                     
{"key" : "C05","code" : "C05135","name" : "지역CH 케이블링/환경공사-전주,대구,낙동"},           
{"key" : "C05","code" : "C05136","name" : "MCS-큐릭스"},                                        
{"key" : "C05","code" : "C05137","name" : "MCS-강서,동대문,새롬,서해"},                         
{"key" : "C05","code" : "C05138","name" : "MCS-한빛,ABC,남동,기남"},                            
{"key" : "C05","code" : "C05139","name" : "MCS-수원"},                                          
{"key" : "C04","code" : "C04030","name" : "VOD Storage 12,000시간"},                            
{"key" : "C05","code" : "C05141","name" : "MCS-중부"},                                          
{"key" : "C05","code" : "C05142","name" : "MCS-전주,대구,낙동"},                                
{"key" : "C05","code" : "C05143","name" : "통합 SI - 큐릭스"},                                  
{"key" : "C05","code" : "C05144","name" : "통합 SI - 강서,동대문,새롬,서해"},                   
{"key" : "C05","code" : "C05145","name" : "통합 SI - 한빛,ABC,남동,기남"},                      
{"key" : "C05","code" : "C05146","name" : "통합 SI - 수원"},                                    
{"key" : "C04","code" : "C04031","name" : "VOD DAS Storage"},                                   
{"key" : "C05","code" : "C05148","name" : "통합 SI - 중부"},                                    
{"key" : "C05","code" : "C05149","name" : "통합 SI - 전주,대구,낙동"},                          
{"key" : "C04","code" : "C04037","name" : "RFGW Chassis"},                                      
{"key" : "C05","code" : "C05150","name" : "통합 SI추가분"},                                     
{"key" : "C05","code" : "C05151","name" : "통합 SI추가분(큐릭스)"},                             
{"key" : "B02","code" : "B02015","name" : "ASR 9006"},                                          
{"key" : "B19","code" : "B19004","name" : "대용량 Firewall/VPN"},                               
{"key" : "C04","code" : "C04042","name" : "RFGW P/S AC"},                                       
{"key" : "B19","code" : "B19002","name" : "소용량 Firewall/VPN"},                               
{"key" : "B19","code" : "B19003","name" : "중용량 Firewall/VPN"},                               
{"key" : "B20","code" : "B20001","name" : "NMS"},                                               
{"key" : "B19","code" : "B19005","name" : "SSL VPN"},                                           
{"key" : "C04","code" : "C04047","name" : "RFGW Module 2Port"},                                 
{"key" : "B04","code" : "B04009","name" : "NMS Server"},                                        
{"key" : "B21","code" : "B21001","name" : "H/W Active 단말"},                                   
{"key" : "B21","code" : "B21002","name" : "S/W Active 단말 S/W 패키지"},                        
{"key" : "B11","code" : "B11013","name" : "IP-DECT Phone"},                                     
{"key" : "C04","code" : "C04052","name" : "케이블 및 잡자재"},                                  
{"key" : "C04","code" : "C04053","name" : "디지털광고서버"},                                    
{"key" : "B04","code" : "B04010","name" : "망 이용료 분석 시스템(수집서버)"},                   
{"key" : "B04","code" : "B04011","name" : "망 이용료 분석 시스템(TAP 및 Aggregator)"},          
{"key" : "C02","code" : "C02009","name" : "삼성 HD용 아답터"},                                  
{"key" : "A02","code" : "A02032","name" : "감쇄기(동양-옥외)"},                                 
{"key" : "C04","code" : "C04058","name" : "디지털광고 서버 및 삽입기 통합 SI"},                 
{"key" : "A02","code" : "A02033","name" : "하향등화기(동양-옥외)"},                             
{"key" : "A02","code" : "A02034","name" : "하향역등화기(동양-옥외)"},                           
{"key" : "A07","code" : "A07072","name" : "PS걸이"},                                            
{"key" : "A13","code" : "A13006","name" : "콘크리트 전주"},                                     
{"key" : "C04","code" : "C04059","name" : "HSD-100V(8VSB 변조기)"},                             
{"key" : "B11","code" : "B11014","name" : "라마다 호텔 PBX"},                                   
{"key" : "B11","code" : "B11015","name" : "IP-DECT Phone Base"},                                
{"key" : "C14","code" : "C14006","name" : "Tripod"},                                            
{"key" : "C06","code" : "C06010","name" : "중부 제작센터 이전 공사"},                           
{"key" : "C15","code" : "C15021","name" : "Swither/Audio"},                                     
{"key" : "C15","code" : "C15022","name" : "Switcher/Video"},                                    
{"key" : "C14","code" : "C14007","name" : "6mm Camcorder"},                                     
{"key" : "C15","code" : "C15023","name" : "Moduler System"},                                    
{"key" : "C15","code" : "C15024","name" : "Patch-Bay System"},                                  
{"key" : "C15","code" : "C15025","name" : "Monitoring System"},                                 
{"key" : "C15","code" : "C15026","name" : "환경 설비 및 설치비"},                               
{"key" : "C04","code" : "C04060","name" : "SDI Router"},                                        
{"key" : "C04","code" : "C04061","name" : "8VSB 계측기"},                                       
{"key" : "C04","code" : "C04062","name" : "8VSB 수신기"},                                       
{"key" : "C04","code" : "C04063","name" : "Auto Change Over"},                                  
{"key" : "C04","code" : "C04064","name" : "DHCP Server"},                                       
{"key" : "C04","code" : "C04065","name" : "ALC (Automatic Loudness Control)"},                  
{"key" : "C15","code" : "C15027","name" : "광전송 VDE RT(4CH)"},                                
{"key" : "C15","code" : "C15028","name" : "VPN (SecuwayGate)"},                                 
{"key" : "C15","code" : "C15029","name" : "보도정보시스템"},                                    
{"key" : "C15","code" : "C15030","name" : "보도정보시스템(수원)"},                              
{"key" : "A12","code" : "A12061","name" : "휴대용계측기 밧데리"},                               
{"key" : "B11","code" : "B11016","name" : "스카이파크 명동 PBX"},                               
{"key" : "ZZZ","code" : "ZZZZZZ","name" : "값없음"},                                            
{"key" : "B02","code" : "B02016","name" : "Catalyst-4503"},                                     
{"key" : "C15","code" : "C15031","name" : "HD전환 - 방송시스템 구축공사(수원)"},                
{"key" : "C15","code" : "C15032","name" : "HD전환 - Tapeless시스템 구축(수원)"},                
{"key" : "C15","code" : "C15033","name" : "HD전환 - ENG Camera(500) : 수원"},                   
{"key" : "C15","code" : "C15034","name" : "HD전환 - ENG Camera(350) : 수원"},                   
{"key" : "C15","code" : "C15035","name" : "HD전환 - VCR"},                                      
{"key" : "C15","code" : "C15036","name" : "HD전환 - EFP Camera : 수원"},                        
{"key" : "C15","code" : "C15037","name" : "HD전환 - 조명설비 구축공사 : 수원"},                 
{"key" : "C15","code" : "C15038","name" : "HD전환 - 방송시스템 구축공사(강서)"},                
{"key" : "C15","code" : "C15039","name" : "HD전환 - Tapeless시스템 구축(강서)"},                
{"key" : "C15","code" : "C15040","name" : "HD전환 - ENG Camera(500) : 강서"},                   
{"key" : "C15","code" : "C15041","name" : "HD전환 - ENG Camera(350) : 강서"},                   
{"key" : "C15","code" : "C15042","name" : "HD전환 - EFP Camera : 강서"},                        
{"key" : "C15","code" : "C15043","name" : "HD전환 - 조명설비 구축공사 : 강서"},                 
{"key" : "A12","code" : "A12062","name" : "휴대용계측기 충전기"},                               
{"key" : "B02","code" : "B02017","name" : "망 이용대가 시스템"},                                
{"key" : "C03","code" : "C03007","name" : "아날로그복조기"},                                    
{"key" : "C04","code" : "C04066","name" : "HD 8VSB Modulator"},                                 
{"key" : "C04","code" : "C04067","name" : "HD 8VSB Remodulator"},                               
{"key" : "C04","code" : "C04068","name" : "16Ch Multi View System"},                            
{"key" : "C04","code" : "C04069","name" : "VDA(10Ch)"},                                         
{"key" : "C15","code" : "C15044","name" : "BIS 프로그램,광고, 편성/관리"},                      
{"key" : "C15","code" : "C15045","name" : "BIS H/W"},                                           
{"key" : "C15","code" : "C15046","name" : "BIS IMS 연동/개발"},                                 
{"key" : "C03","code" : "C03008","name" : "지상파 D to A 시스템"},                              
{"key" : "C03","code" : "C03009","name" : "A/V 자동절체기"},                                    
{"key" : "C04","code" : "C04070","name" : "8VSB 변조기"},                                       
{"key" : "C04","code" : "C04071","name" : "자막기"},                                            
{"key" : "C15","code" : "C15047","name" : "지역채널Application"},                               
{"key" : "A09","code" : "A09036","name" : "광접속함체(인입간선)"},                              
{"key" : "B04","code" : "B04012","name" : "IP망 NMS DB Server"},                                
{"key" : "C04","code" : "C04072","name" : "HD Encoder Modulator"},                              
{"key" : "C04","code" : "C04073","name" : "강서방송 메이필드호텔 (Combiner외)"},                
{"key" : "B04","code" : "B04013","name" : "광랜/전용선 전산 개발"},                             
{"key" : "B04","code" : "B04014","name" : "광랜/전용선 전산용 Server"},                         
{"key" : "C09","code" : "C09010","name" : "MLBS(Mobile Live Broadcasting System)"},             
{"key" : "C09","code" : "C09011","name" : "디스크레코더"},                                      
{"key" : "C09","code" : "C09012","name" : "NLE(Nonlinear Editing System)"},                     
{"key" : "C14","code" : "C14008","name" : "HD 광송수신기"},                                     
{"key" : "C14","code" : "C14009","name" : "Scan Converter"},                                    
{"key" : "B22","code" : "B22001","name" : "E-PON"},                                             
{"key" : "B22","code" : "B22002","name" : "RN"},                                                
{"key" : "B11","code" : "B11017","name" : "서울내과 IP-LDK 300/600"},                           
{"key" : "B22","code" : "B22003","name" : "E-PON ONU"},                                         
{"key" : "B22","code" : "B22004","name" : "E-PON ONU Up-Link Module"},                          
{"key" : "C14","code" : "C14010","name" : "경기교통센터 CCTV 수신 장비"},                       
{"key" : "C04","code" : "C04074","name" : "Castanets CFMS-N900"},                               
{"key" : "C04","code" : "C04075","name" : "VOD시스템"},                                         
{"key" : "B11","code" : "B11020","name" : "미래신용정보 IP PBX"},                               
{"key" : "C04","code" : "C04076","name" : "QAM to 8VSB"},                                       
{"key" : "B11","code" : "B11021","name" : "스카이파크호텔 4호점"},                              
{"key" : "C04","code" : "C04077","name" : "RF 자동절체기"},                                     
{"key" : "A07","code" : "A07074","name" : "지선그립"},                                          
{"key" : "A12","code" : "A12063","name" : "FSH4_Spectrum set"},                                 
{"key" : "A12","code" : "A12064","name" : "HE300(Antenna)"},                                    
{"key" : "C05","code" : "C05153","name" : "HD Upgrade"},                                        
{"key" : "C09","code" : "C09013","name" : "중계차"},                                            
{"key" : "C05","code" : "C05152","name" : "APC System"},                                        
{"key" : "C05","code" : "C05154","name" : "CMS 성능 개선"},                                     
{"key" : "C05","code" : "C05157","name" : "SP-0092-001"},                                       
{"key" : "C05","code" : "C05158","name" : "MCP-2201-41C"}]