[
{"com_id" : "A411","com_name" : "(주)티브로드에이비씨방송"},      
{"com_id" : "A412","com_name" : "(주)티브로드 수원방송"},         
{"com_id" : "A413","com_name" : "(주)티브로드 전주방송"},         
{"com_id" : "A414","com_name" : "(주)티브로드 중부방송"},         
{"com_id" : "A415","com_name" : "(주)티브로드 남동방송"},         
{"com_id" : "A416","com_name" : "(주)티브로드 기남방송"},         
{"com_id" : "A417","com_name" : "(주)티브로드 낙동방송"},         
{"com_id" : "A418","com_name" : "(주)티브로드 동남방송"},         
{"com_id" : "A419","com_name" : "(주)티브로드 서부산방송"},       
{"com_id" : "A420","com_name" : "(주)티브로드 강서방송"},         
{"com_id" : "A421","com_name" : "(주)티브로드 새롬방송"},         
{"com_id" : "A422","com_name" : "(주)티브로드 티씨엔방송"},       
{"com_id" : "C120","com_name" : "(주)티브로드서해방송"},          
{"com_id" : "K110","com_name" : "(주)아이디지털홈쇼핑"},          
{"com_id" : "J111","com_name" : "(주)티브로드 서대문방송"},       
{"com_id" : "J112","com_name" : "(주)티브로드 광진성동방송"},     
{"com_id" : "J113","com_name" : "(주)티브로드 종로중구방송"},     
{"com_id" : "J114","com_name" : "(주)티브로드 대구방송"},         
{"com_id" : "J115","com_name" : "(주)티브로드 대경방송"},         
{"com_id" : "J110","com_name" : "(주)티브로드도봉강북방송"},      
{"com_id" : "J140","com_name" : "(주)티브로드노원방송"},          
{"com_id" : "A410","com_name" : "(주)티브로드한빛방송"},          
{"com_id" : "G110","com_name" : "(주)티브로드 동대문방송"},       
{"com_id" : "H150","com_name" : "(주)티브로드홀딩스"},            
{"com_id" : "J180","com_name" : "(주)큐릭스홀딩스"},              
{"com_id" : "V110","com_name" : "(주)한국케이블텔레콤"},          
{"com_id" : "Y120","com_name" : "(주)한국디지털케이블미디어센터"},
{"com_id" : "Y140","com_name" : "(주)티캐스트"},                  
{"com_id" : "Y160","com_name" : "(주)티피엔에스"},                
{"com_id" : "Y110","com_name" : "(주)이채널"},                    
{"com_id" : "Y130","com_name" : "(주)티캐스트콘텐츠허브"},        
{"com_id" : "Y150","com_name" : "씨네큐브 광화문"},               
{"com_id" : "M110","com_name" : "MSO본부"}]
