[{"code" : "A","value" : "업체설계"},                       
{"code" : "B","value" : "설계완료(업체)"},                 
{"code" : "C","value" : "설계복사"},                       
{"code" : "D","value" : "설계생성(SO)"},                   
{"code" : "E","value" : "변경대기"},                       
{"code" : "F","value" : "SO 설계"},                        
{"code" : "G","value" : "설계반려"},                       
{"code" : "H","value" : "설계완료(SO)"},                   
{"code" : "M","value" : "SO 결재"},                        
{"code" : "O","value" : "공사승인"},                       
{"code" : "P","value" : "공사마감"},                       
{"code" : "Q","value" : "준공저장"},                       
{"code" : "R","value" : "준공완료"},                       
{"code" : "S","value" : "준공결재"},                       
{"code" : "T","value" : "공사정산"},                       
{"code" : "Z","value" : "삭제"}]                           
